using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TourCompany.Application.Common.Interfaces;
using TourCompany.Domain.Entities;

namespace TourCompany.Infrastructure.Persistence
{
    public class DataSeed
    {
        public static void SeedContext(ITourCompanyDbContext context)
        {
#if DEBUG
            var languages = new Language[]
            {
                new Language("Dutch"),
                new Language("English"),
                new Language("Finnish"),
                new Language("Greek"),
                new Language("Japanese"),
                new Language("Ukrainian"),
            };
            context.Instance.Add(languages);


            var countries = new Country[]
            {
                new Country("Finland"),//1
                new Country("Greece"),//2
                new Country("Italy"),//3
                new Country("Japan"),//4
                new Country("Netherlands"),//5
                new Country("Ukraine"),//6
                new Country("United Kingdom"),//7
            };
            context.Instance.Add(countries);


            var nationalities = new Nationality[]
            {
                new Nationality("Dutch"),//1
                new Nationality("English"),//2
                new Nationality("Finnish"),//3
                new Nationality("Greek"),//4
                new Nationality("Japanese"),//5
                new Nationality("Ukrainian"),//6
            };
            context.Instance.Add(nationalities);

            var genders = new Gender[]
            {
                new Gender("Male"),//1
                new Gender("Female")//2
            };
            context.Instance.Add(genders);
            con
            var tourists = new Tourist[]
            {
                new Tourist("System", DateTime.Now)
                {
                    Name = "Levi",
                    Surname = "Acevedo",
                    BirthDate = new DateTime(1991, 06, 11),
                    CountryID = 3,
                    GenderID = 2,
                    NationalityID = 5,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Basil",
                    Surname = "Aguilar",
                    BirthDate = new DateTime(1994, 04, 22),
                    CountryID = 2,
                    GenderID = 1,
                    NationalityID = 4,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Zenaida",
                    Surname = "Holder",
                    BirthDate = new DateTime(1990, 01, 09),
                    CountryID = 2,
                    GenderID = 1,
                    NationalityID = 3,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Illana",
                    Surname = "Browning",
                    BirthDate = new DateTime(1991, 01, 28),
                    CountryID = 7,
                    GenderID = 2,
                    NationalityID = 4,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Raja",
                    Surname = "Duke",
                    BirthDate = new DateTime(1983, 07, 27),
                    CountryID = 5,
                    GenderID = 1,
                    NationalityID = 1,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Isaiah",
                    Surname = "Valdez",
                    BirthDate = new DateTime(1998, 01, 16),
                    CountryID = 1,
                    GenderID = 1,
                    NationalityID = 3,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Gray",
                    Surname = "Marshall",
                    BirthDate = new DateTime(1980, 11, 21),
                    CountryID = 4,
                    GenderID = 2,
                    NationalityID = 5,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Ora",
                    Surname = "Fletcher",
                    BirthDate = new DateTime(1994, 01, 19),
                    CountryID = 7,
                    GenderID = 2,
                    NationalityID = 2,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Lavinia",
                    Surname = "Lloyd",
                    BirthDate = new DateTime(1986, 10, 26),
                    CountryID = 7,
                    GenderID = 2,
                    NationalityID = 2,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Jenna",
                    Surname = "Williams",
                    BirthDate = new DateTime(1982, 05, 01),
                    CountryID = 2,
                    GenderID = 2,
                    NationalityID = 4,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Christian",
                    Surname = "Nash",
                    BirthDate = new DateTime(1980, 08, 09),
                    CountryID = 7,
                    GenderID = 1,
                    NationalityID = 2,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Levi",
                    Surname = "Acevedo",
                    BirthDate = new DateTime(1991, 06, 11),
                    CountryID = 3,
                    GenderID = 2,
                    NationalityID = 5,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Levi",
                    Surname = "Acevedo",
                    BirthDate = new DateTime(1991, 06, 11),
                    CountryID = 3,
                    GenderID = 2,
                    NationalityID = 5,
                },
                new Tourist("System", DateTime.Now)
                {
                    Name = "Levi",
                    Surname = "Acevedo",
                    BirthDate = new DateTime(1991, 06, 11),
                    CountryID = 3,
                    GenderID = 2,
                    NationalityID = 5,
                },
            };

            var destinations = new Destination[]
            {
                new Destination("Ayasofya", 20.00m, "System", DateTime.Now),
                new Destination("Yerebatan Sarnıcı", 30.00m, "System", DateTime.Now),
                new Destination("Pierre Loti", 20.00m, "System", DateTime.Now),
                new Destination("Kız Kulesi", 20.00m, "System", DateTime.Now),
                new Destination("Adalar", 20.00m, "System", DateTime.Now),
                new Destination("Dolmabahçe Sarayı", 20.00m, "System", DateTime.Now),
                new Destination("Miniatürk", 20.00m, "System", DateTime.Now),
                new Destination("Sultan Ahmet Camii", 20.00m, "System", DateTime.Now),
                new Destination("Rumeli Hisarı", 20.00m, "System", DateTime.Now),
                new Destination("Anadolu Hisarı", 20.00m, "System", DateTime.Now),
                new Destination("Eyüp Sultan Camii", 20.00m, "System", DateTime.Now),
                new Destination("Atatürk Arboretumu", 20.00m, "System", DateTime.Now),
                new Destination("Kapalı Çarşı", 20.00m, "System", DateTime.Now),
                new Destination("Mısır Çarşısı", 20.00m, "System", DateTime.Now),
            };
            context.Instance.Add(destinations);

            var guides = new Guide[]
            {
                new Guide("Ozan", "Temiz", "5556544343", 1, true, "System", DateTime.Now),
                new Guide("Bahar", "Sevgin", "5556544344", 2, true, "System", DateTime.Now),
                new Guide("Ömer", "Uçar", "5556544345", 1, true, "System", DateTime.Now),
                new Guide("Sevgi", "Çakmak", "5556544346", 2, true, "System", DateTime.Now),
                new Guide("Linda", "Callahan", "5556544349", 2, true, "System", DateTime.Now),
            };
            context.Instance.Add(guides);
#else
var languages = new Language[]
            {
                new Language("Afrikaans"),
                new Language("Albanian"),
                new Language("Amharic"),
                new Language("Arabic"),
                new Language("Armenian"),
                new Language("Aymara"),
                new Language("Azerbaijani"),
                new Language("Bahasa Indonesia"),
                new Language("Bahasa Malaysia"),
                new Language("Belarusian"),
                new Language("Bengali"),
                new Language("Bosnian"),
                new Language("Bulgarian"),
                new Language("Burmanese"),
                new Language("Cantonese"),
                new Language("Catalan"),
                new Language("Chamorro"),
                new Language("Cook Island Maori"),
                new Language("Creole"),
                new Language("Croatian"),
                new Language("Czech"),
                new Language("Danish"),
                new Language("Dari"),
                new Language("Dhivehi"),
                new Language("Dutch"),
                new Language("Dzongkha"),
                new Language("English"),
                new Language("Estonian"),
                new Language("Faroese"),
                new Language("Fijian"),
                new Language("Filipino"),
                new Language("Finnish"),
                new Language("French"),
                new Language("Georgian"),
                new Language("German"),
                new Language("Greek"),
                new Language("Greenlandic"),
                new Language("Guarani"),
                new Language("Hebrew"),
                new Language("Hindi"),
                new Language("Hiri Motu"),
                new Language("Hungarian"),
                new Language("Icelandic"),
                new Language("Indigenous"),
                new Language("Irish"),
                new Language("Italian"),
                new Language("Japanese"),
                new Language("Karakalpakstani"),
                new Language("Kazakh"),
                new Language("Khalkha Mongol"),
                new Language("Khmer"),
                new Language("Kinyarwanda"),
                new Language("Kirundi"),
                new Language("Kiswahili"),
                new Language("Korean"),
                new Language("Kurdish"),
                new Language("Kyrgyz"),
                new Language("Lao"),
                new Language("Latin"),
                new Language("Latvian"),
                new Language("Lingala"),
                new Language("Lithuanian"),
                new Language("Luxembourgish"),
                new Language("Macedonian"),
                new Language("Malagasy"),
                new Language("Malay"),
                new Language("Maltese"),
                new Language("Maori"),
                new Language("Marshallese"),
                new Language("Melanesian pidgin"),
                new Language("Mirandese"),
                new Language("Moldovan"),
                new Language("Montenegrin"),
                new Language("Nauruan"),
                new Language("Ndebele"),
                new Language("Nepali"),
                new Language("Niuean"),
                new Language("Norwegian"),
                new Language("Palauan"),
                new Language("Pashto"),
                new Language("Persian"),
                new Language("Polish"),
                new Language("Polynesian"),
                new Language("Portuguese"),
                new Language("Quechua"),
                new Language("Regional Chinese"),
                new Language("Romanian"),
                new Language("Russian"),
                new Language("Samoan"),
                new Language("Sangho"),
                new Language("Sara"),
                new Language("Serbian"),
                new Language("Shona"),
                new Language("Sinhala"),
                new Language("Slovak"),
                new Language("Slovenian"),
                new Language("Somali"),
                new Language("Sotho"),
                new Language("Spanish"),
                new Language("Standard Chinese or Mandarin"),
                new Language("Swahili"),
                new Language("Swedish"),
                new Language("Tajik"),
                new Language("Tetum"),
                new Language("Thai"),
                new Language("Tigrinya"),
                new Language("Tok Pisin"),
                new Language("Tongan"),
                new Language("Turkish"),
                new Language("Turkmen"),
                new Language("Tuvaluan"),
                new Language("Ukrainian"),
                new Language("Urdu"),
                new Language("Uzbek"),
                new Language("Vietnamese"),
                new Language("siSwati"),
            };
            context.Instance.Add(languages);


            var countries = new Country[]
            {
                new Country("Afghanistan"),
                new Country("Albania"),
                new Country("Algeria"),
                new Country("Andorra"),
                new Country("Angola"),
                new Country("Antigua and Barbuda"),
                new Country("Argentina"),
                new Country("Armenia"),
                new Country("Australia"),
                new Country("Norfolk Island"),
                new Country("Austria"),
                new Country("Azerbaijan"),
                new Country("Bahrain"),
                new Country("Bangladesh"),
                new Country("Barbados"),
                new Country("Belarus"),
                new Country("Belgium"),
                new Country("Belize"),
                new Country("Benin"),
                new Country("Bhutan"),
                new Country("Bolivia"),
                new Country("Bosnia and Herzegovina"),
                new Country("Botswana"),
                new Country("Brazil"),
                new Country("Brunei"),
                new Country("Bulgaria"),
                new Country("Burkina Faso"),
                new Country("Burundi"),
                new Country("Cambodia"),
                new Country("Cameroon"),
                new Country("Canada"),
                new Country("Cape Verde"),
                new Country("Central African Republic"),
                new Country("Chad"),
                new Country("Chile"),
                new Country("China"),
                new Country("Hong Kong S.A.R."),
                new Country("Colombia"),
                new Country("Comoros"),
                new Country("Costa Rica"),
                new Country("Croatia"),
                new Country("Cuba"),
                new Country("Cyprus"),
                new Country("Czech Republic"),
                new Country("Democratic Republic of the Congo"),
                new Country("Denmark"),
                new Country("Faroe Islands"),
                new Country("Greenland"),
                new Country("Djibouti"),
                new Country("Dominica"),
                new Country("Dominican Republic"),
                new Country("East Timor"),
                new Country("Ecuador"),
                new Country("Egypt"),
                new Country("El Salvador"),
                new Country("Equatorial Guinea"),
                new Country("Eritrea"),
                new Country("Estonia"),
                new Country("Ethiopia"),
                new Country("Federated States of Micronesia"),
                new Country("Fiji"),
                new Country("Aland"),
                new Country("Finland"),
                new Country("Clipperton Island"),
                new Country("France"),
                new Country("French Polynesia"),
                new Country("New Caledonia"),
                new Country("Saint Barthelemy"),
                new Country("Saint Martin"),
                new Country("Saint Pierre and Miquelon"),
                new Country("Wallis and Futuna"),
                new Country("Gabon"),
                new Country("Gambia"),
                new Country("Georgia"),
                new Country("Germany"),
                new Country("Ghana"),
                new Country("Greece"),
                new Country("Grenada"),
                new Country("Guatemala"),
                new Country("Guinea"),
                new Country("Guinea Bissau"),
                new Country("Guyana"),
                new Country("Haiti"),
                new Country("Honduras"),
                new Country("Hungary"),
                new Country("Iceland"),
                new Country("India"),
                new Country("Indonesia"),
                new Country("Iran"),
                new Country("Iraq"),
                new Country("Ireland"),
                new Country("Israel"),
                new Country("Palestine"),
                new Country("Italy"),
                new Country("Ivory Coast"),
                new Country("Jamaica"),
                new Country("Japan"),
                new Country("Jordan"),
                new Country("Kazakhstan"),
                new Country("Kenya"),
                new Country("Kiribati"),
                new Country("Kosovo"),
                new Country("Kuwait"),
                new Country("Kyrgyzstan"),
                new Country("Laos"),
                new Country("Latvia"),
                new Country("Lebanon"),
                new Country("Lesotho"),
                new Country("Liberia"),
                new Country("Libya"),
                new Country("Liechtenstein"),
                new Country("Lithuania"),
                new Country("Luxembourg"),
                new Country("Macedonia"),
                new Country("Madagascar"),
                new Country("Malawi"),
                new Country("Malaysia"),
                new Country("Maldives"),
                new Country("Mali"),
                new Country("Malta"),
                new Country("Marshall Islands"),
                new Country("Mauritania"),
                new Country("Mauritius"),
                new Country("Mexico"),
                new Country("Moldova"),
                new Country("Monaco"),
                new Country("Mongolia"),
                new Country("Montenegro"),
                new Country("Morocco"),
                new Country("Mozambique"),
                new Country("Myanmar"),
                new Country("Namibia"),
                new Country("Nauru"),
                new Country("Nepal"),
                new Country("Aruba"),
                new Country("Netherlands"),
                new Country("Sint Maarten"),
                new Country("Cook Islands"),
                new Country("New Zealand"),
                new Country("Niue"),
                new Country("Nicaragua"),
                new Country("Niger"),
                new Country("Nigeria"),
                new Country("North Korea"),
                new Country("Northern Cyprus"),
                new Country("Norway"),
                new Country("Oman"),
                new Country("Pakistan"),
                new Country("Palau"),
                new Country("Panama"),
                new Country("Papua New Guinea"),
                new Country("Paraguay"),
                new Country("Peru"),
                new Country("Philippines"),
                new Country("Poland"),
                new Country("Portugal"),
                new Country("Qatar"),
                new Country("Republic of Congo"),
                new Country("Serbia"),
                new Country("Romania"),
                new Country("Russia"),
                new Country("Rwanda"),
                new Country("Saint Kitts and Nevis"),
                new Country("Saint Lucia"),
                new Country("Saint Vincent and the Grenadines"),
                new Country("Samoa"),
                new Country("San Marino"),
                new Country("Sao Tome and Principe"),
                new Country("Saudi Arabia"),
                new Country("Senegal"),
                new Country("Seychelles"),
                new Country("Sierra Leone"),
                new Country("Singapore"),
                new Country("Slovakia"),
                new Country("Slovenia"),
                new Country("Solomon Islands"),
                new Country("Somalia"),
                new Country("Somaliland"),
                new Country("South Africa"),
                new Country("South Korea"),
                new Country("South Sudan"),
                new Country("Spain"),
                new Country("Sri Lanka"),
                new Country("Sudan"),
                new Country("Suriname"),
                new Country("Swaziland"),
                new Country("Sweden"),
                new Country("Switzerland"),
                new Country("Syria"),
                new Country("Taiwan"),
                new Country("Tajikistan"),
                new Country("Thailand"),
                new Country("Togo"),
                new Country("Tonga"),
                new Country("Trinidad and Tobago"),
                new Country("Tunisia"),
                new Country("Turkey"),
                new Country("Turkmenistan"),
                new Country("Tuvalu"),
                new Country("Uganda"),
                new Country("Ukraine"),
                new Country("United Arab Emirates"),
                new Country("Anguilla"),
                new Country("Bermuda"),
                new Country("British Indian Ocean Territory"),
                new Country("British Virgin Islands"),
                new Country("Cayman Islands"),
                new Country("Falkland Islands"),
                new Country("Gibraltar"),
                new Country("Guernsey"),
                new Country("Isle of Man"),
                new Country("Jersey"),
                new Country("Montserrat"),
                new Country("Pitcairn Islands"),
                new Country("Saint Helena"),
                new Country("Turks and Caicos Islands"),
                new Country("United Kingdom"),
                new Country("United Republic of Tanzania"),
                new Country("American Samoa"),
                new Country("Guam"),
                new Country("Northern Mariana Islands"),
                new Country("Puerto Rico"),
                new Country("United States Minor Outlying Islands"),
                new Country("United States of America"),
                new Country("Uruguay"),
                new Country("Uzbekistan"),
                new Country("Vanuatu"),
                new Country("Vatican"),
                new Country("Venezuela"),
                new Country("Vietnam"),
                new Country("Western Sahara"),
                new Country("Yemen"),
                new Country("Zambia"),
                new Country("Zimbabwe"),
            };
            context.Instance.Add(countries);


            var nationalities = new Nationality[]
            {
                new Nationality("Afghan"),
                new Nationality("Albanian"),
                new Nationality("Andorran"),
                new Nationality("Angolan"),
                new Nationality("Argentine"),
                new Nationality("Armenian"),
                new Nationality("Azerbaijani"),
                new Nationality("Bahamian"),
                new Nationality("Bahraini"),
                new Nationality("Belarusian"),
                new Nationality("Belgian"),
                new Nationality("Bermudian"),
                new Nationality("Bhutanese"),
                new Nationality("Botswanan"),
                new Nationality("Brazilian"),
                new Nationality("Bruneian"),
                new Nationality("Bulgarian"),
                new Nationality("Burundian"),
                new Nationality("Cambodian"),
                new Nationality("Cameroonian"),
                new Nationality("Cayman Islander"),
                new Nationality("Central African"),
                new Nationality("Chinese"),
                new Nationality("Citizen of Seychelles"),
                new Nationality("Citizen of Vanuatu"),
                new Nationality("Colombian"),
                new Nationality("Congolese (DRC)"),
                new Nationality("Cook Islander"),
                new Nationality("Cuban"),
                new Nationality("Cymraes"),
                new Nationality("Czech"),
                new Nationality("Danish"),
                new Nationality("Djiboutian"),
                new Nationality("Dutch"),
                new Nationality("East Timorese"),
                new Nationality("Ecuadorean"),
                new Nationality("English"),
                new Nationality("Equatorial Guinean"),
                new Nationality("Ethiopian"),
                new Nationality("Faroese"),
                new Nationality("Fijian"),
                new Nationality("Finnish"),
                new Nationality("French"),
                new Nationality("Gabonese"),
                new Nationality("Gambian"),
                new Nationality("Ghanaian"),
                new Nationality("Gibraltarian"),
                new Nationality("Greek"),
                new Nationality("Grenadian"),
                new Nationality("Guamanian"),
                new Nationality("Guinean"),
                new Nationality("Guyanese"),
                new Nationality("Haitian"),
                new Nationality("Honduran"),
                new Nationality("Icelandic"),
                new Nationality("Indian"),
                new Nationality("Iraqi"),
                new Nationality("Italian"),
                new Nationality("Irish"),
                new Nationality("Ivorian"),
                new Nationality("Jamaican"),
                new Nationality("Japanese"),
                new Nationality("Kazakh"),
                new Nationality("Kenyan"),
                new Nationality("Kosovan"),
                new Nationality("Kuwaiti"),
                new Nationality("Lao"),
                new Nationality("Latvian"),
                new Nationality("Libyan"),
                new Nationality("Liechtenstein citizen"),
                new Nationality("Macanese"),
                new Nationality("Macedonian"),
                new Nationality("Malaysian"),
                new Nationality("Maldivian"),
                new Nationality("Marshallese"),
                new Nationality("Martiniquais"),
                new Nationality("Mexican"),
                new Nationality("Micronesian"),
                new Nationality("Mongolian"),
                new Nationality("Montenegrin"),
                new Nationality("Mosotho"),
                new Nationality("Mozambican"),
                new Nationality("Namibian"),
                new Nationality("Nauruan"),
                new Nationality("Nicaraguan"),
                new Nationality("Nigerian"),
                new Nationality("North Korean"),
                new Nationality("Northern Irish"),
                new Nationality("Omani"),
                new Nationality("Pakistani"),
                new Nationality("Palauan"),
                new Nationality("Papua New Guinean"),
                new Nationality("Paraguayan"),
                new Nationality("Polish"),
                new Nationality("Portuguese"),
                new Nationality("Qatari"),
                new Nationality("Romanian"),
                new Nationality("Russian"),
                new Nationality("Salvadorean"),
                new Nationality("Sammarinese"),
                new Nationality("Saudi Arabian"),
                new Nationality("Scottish"),
                new Nationality("Sierra Leonean"),
                new Nationality("Slovenian"),
                new Nationality("Solomon Islander"),
                new Nationality("South Korean"),
                new Nationality("South Sudanese"),
                new Nationality("St Helenian"),
                new Nationality("St Lucian"),
                new Nationality("Surinamese"),
                new Nationality("Swazi"),
                new Nationality("Syrian"),
                new Nationality("Taiwanese"),
                new Nationality("Tajik"),
                new Nationality("Togolese"),
                new Nationality("Tongan"),
                new Nationality("Tunisian"),
                new Nationality("Turkish"),
                new Nationality("Tuvaluan"),
                new Nationality("Ugandan"),
                new Nationality("Ukrainian"),
                new Nationality("Vatican citizen"),
                new Nationality("Vincentian"),
                new Nationality("Wallisian"),
                new Nationality("Welsh"),
                new Nationality("Yemeni"),
                new Nationality("Zambian"),
                new Nationality("Zimbabwean"),
            };
            context.Instance.Add(nationalities);

            var genders = new Gender[]
            {
                new Gender("Male"),
                new Gender("Female")
            };
            context.Instance.Add(genders); 
#endif
        }
    }
}
