// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourCompany.Infrastructure.Persistence;

#nullable disable

namespace TourCompany.Infrastructure.Migrations
{
    [DbContext(typeof(TourCompanyDbContext))]
    [Migration("20220713135048_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TourCompany.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GuideID")
                        .HasColumnType("int");

                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("GuideID");

                    b.HasIndex("TourID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            CountryID = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            CountryID = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            CountryID = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            CountryID = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            CountryID = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryID = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryID = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            CountryID = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            CountryID = 10,
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            CountryID = 11,
                            Name = "Austria"
                        },
                        new
                        {
                            CountryID = 12,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            CountryID = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            CountryID = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            CountryID = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            CountryID = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            CountryID = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryID = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            CountryID = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            CountryID = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            CountryID = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            CountryID = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryID = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            CountryID = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryID = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            CountryID = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            CountryID = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            CountryID = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            CountryID = 29,
                            Name = "Cambodia"
                        },
                        new
                        {
                            CountryID = 30,
                            Name = "Cameroon"
                        },
                        new
                        {
                            CountryID = 31,
                            Name = "Canada"
                        },
                        new
                        {
                            CountryID = 32,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            CountryID = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            CountryID = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            CountryID = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            CountryID = 36,
                            Name = "China"
                        },
                        new
                        {
                            CountryID = 37,
                            Name = "Hong Kong S.A.R."
                        },
                        new
                        {
                            CountryID = 38,
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryID = 39,
                            Name = "Comoros"
                        },
                        new
                        {
                            CountryID = 40,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryID = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            CountryID = 42,
                            Name = "Cuba"
                        },
                        new
                        {
                            CountryID = 43,
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryID = 44,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            CountryID = 45,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            CountryID = 46,
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryID = 47,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            CountryID = 48,
                            Name = "Greenland"
                        },
                        new
                        {
                            CountryID = 49,
                            Name = "Djibouti"
                        },
                        new
                        {
                            CountryID = 50,
                            Name = "Dominica"
                        },
                        new
                        {
                            CountryID = 51,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            CountryID = 52,
                            Name = "East Timor"
                        },
                        new
                        {
                            CountryID = 53,
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryID = 54,
                            Name = "Egypt"
                        },
                        new
                        {
                            CountryID = 55,
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryID = 56,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryID = 57,
                            Name = "Eritrea"
                        },
                        new
                        {
                            CountryID = 58,
                            Name = "Estonia"
                        },
                        new
                        {
                            CountryID = 59,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            CountryID = 60,
                            Name = "Federated States of Micronesia"
                        },
                        new
                        {
                            CountryID = 61,
                            Name = "Fiji"
                        },
                        new
                        {
                            CountryID = 62,
                            Name = "Aland"
                        },
                        new
                        {
                            CountryID = 63,
                            Name = "Finland"
                        },
                        new
                        {
                            CountryID = 64,
                            Name = "Clipperton Island"
                        },
                        new
                        {
                            CountryID = 65,
                            Name = "France"
                        },
                        new
                        {
                            CountryID = 66,
                            Name = "French Polynesia"
                        },
                        new
                        {
                            CountryID = 67,
                            Name = "New Caledonia"
                        },
                        new
                        {
                            CountryID = 68,
                            Name = "Saint Barthelemy"
                        },
                        new
                        {
                            CountryID = 69,
                            Name = "Saint Martin"
                        },
                        new
                        {
                            CountryID = 70,
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryID = 71,
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryID = 72,
                            Name = "Gabon"
                        },
                        new
                        {
                            CountryID = 73,
                            Name = "Gambia"
                        },
                        new
                        {
                            CountryID = 74,
                            Name = "Georgia"
                        },
                        new
                        {
                            CountryID = 75,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryID = 76,
                            Name = "Ghana"
                        },
                        new
                        {
                            CountryID = 77,
                            Name = "Greece"
                        },
                        new
                        {
                            CountryID = 78,
                            Name = "Grenada"
                        },
                        new
                        {
                            CountryID = 79,
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryID = 80,
                            Name = "Guinea"
                        },
                        new
                        {
                            CountryID = 81,
                            Name = "Guinea Bissau"
                        },
                        new
                        {
                            CountryID = 82,
                            Name = "Guyana"
                        },
                        new
                        {
                            CountryID = 83,
                            Name = "Haiti"
                        },
                        new
                        {
                            CountryID = 84,
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryID = 85,
                            Name = "Hungary"
                        },
                        new
                        {
                            CountryID = 86,
                            Name = "Iceland"
                        },
                        new
                        {
                            CountryID = 87,
                            Name = "India"
                        },
                        new
                        {
                            CountryID = 88,
                            Name = "Indonesia"
                        },
                        new
                        {
                            CountryID = 89,
                            Name = "Iran"
                        },
                        new
                        {
                            CountryID = 90,
                            Name = "Iraq"
                        },
                        new
                        {
                            CountryID = 91,
                            Name = "Ireland"
                        },
                        new
                        {
                            CountryID = 92,
                            Name = "Israel"
                        },
                        new
                        {
                            CountryID = 93,
                            Name = "Palestine"
                        },
                        new
                        {
                            CountryID = 94,
                            Name = "Italy"
                        },
                        new
                        {
                            CountryID = 95,
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            CountryID = 96,
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryID = 97,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryID = 98,
                            Name = "Jordan"
                        },
                        new
                        {
                            CountryID = 99,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            CountryID = 100,
                            Name = "Kenya"
                        },
                        new
                        {
                            CountryID = 101,
                            Name = "Kiribati"
                        },
                        new
                        {
                            CountryID = 102,
                            Name = "Kosovo"
                        },
                        new
                        {
                            CountryID = 103,
                            Name = "Kuwait"
                        },
                        new
                        {
                            CountryID = 104,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryID = 105,
                            Name = "Laos"
                        },
                        new
                        {
                            CountryID = 106,
                            Name = "Latvia"
                        },
                        new
                        {
                            CountryID = 107,
                            Name = "Lebanon"
                        },
                        new
                        {
                            CountryID = 108,
                            Name = "Lesotho"
                        },
                        new
                        {
                            CountryID = 109,
                            Name = "Liberia"
                        },
                        new
                        {
                            CountryID = 110,
                            Name = "Libya"
                        },
                        new
                        {
                            CountryID = 111,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            CountryID = 112,
                            Name = "Lithuania"
                        },
                        new
                        {
                            CountryID = 113,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            CountryID = 114,
                            Name = "Macedonia"
                        },
                        new
                        {
                            CountryID = 115,
                            Name = "Madagascar"
                        },
                        new
                        {
                            CountryID = 116,
                            Name = "Malawi"
                        },
                        new
                        {
                            CountryID = 117,
                            Name = "Malaysia"
                        },
                        new
                        {
                            CountryID = 118,
                            Name = "Maldives"
                        },
                        new
                        {
                            CountryID = 119,
                            Name = "Mali"
                        },
                        new
                        {
                            CountryID = 120,
                            Name = "Malta"
                        },
                        new
                        {
                            CountryID = 121,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            CountryID = 122,
                            Name = "Mauritania"
                        },
                        new
                        {
                            CountryID = 123,
                            Name = "Mauritius"
                        },
                        new
                        {
                            CountryID = 124,
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryID = 125,
                            Name = "Moldova"
                        },
                        new
                        {
                            CountryID = 126,
                            Name = "Monaco"
                        },
                        new
                        {
                            CountryID = 127,
                            Name = "Mongolia"
                        },
                        new
                        {
                            CountryID = 128,
                            Name = "Montenegro"
                        },
                        new
                        {
                            CountryID = 129,
                            Name = "Morocco"
                        },
                        new
                        {
                            CountryID = 130,
                            Name = "Mozambique"
                        },
                        new
                        {
                            CountryID = 131,
                            Name = "Myanmar"
                        },
                        new
                        {
                            CountryID = 132,
                            Name = "Namibia"
                        },
                        new
                        {
                            CountryID = 133,
                            Name = "Nauru"
                        },
                        new
                        {
                            CountryID = 134,
                            Name = "Nepal"
                        },
                        new
                        {
                            CountryID = 135,
                            Name = "Aruba"
                        },
                        new
                        {
                            CountryID = 136,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryID = 137,
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            CountryID = 138,
                            Name = "Cook Islands"
                        },
                        new
                        {
                            CountryID = 139,
                            Name = "New Zealand"
                        },
                        new
                        {
                            CountryID = 140,
                            Name = "Niue"
                        },
                        new
                        {
                            CountryID = 141,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryID = 142,
                            Name = "Niger"
                        },
                        new
                        {
                            CountryID = 143,
                            Name = "Nigeria"
                        },
                        new
                        {
                            CountryID = 144,
                            Name = "North Korea"
                        },
                        new
                        {
                            CountryID = 145,
                            Name = "Northern Cyprus"
                        },
                        new
                        {
                            CountryID = 146,
                            Name = "Norway"
                        },
                        new
                        {
                            CountryID = 147,
                            Name = "Oman"
                        },
                        new
                        {
                            CountryID = 148,
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryID = 149,
                            Name = "Palau"
                        },
                        new
                        {
                            CountryID = 150,
                            Name = "Panama"
                        },
                        new
                        {
                            CountryID = 151,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            CountryID = 152,
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryID = 153,
                            Name = "Peru"
                        },
                        new
                        {
                            CountryID = 154,
                            Name = "Philippines"
                        },
                        new
                        {
                            CountryID = 155,
                            Name = "Poland"
                        },
                        new
                        {
                            CountryID = 156,
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryID = 157,
                            Name = "Qatar"
                        },
                        new
                        {
                            CountryID = 158,
                            Name = "Republic of Congo"
                        },
                        new
                        {
                            CountryID = 159,
                            Name = "Serbia"
                        },
                        new
                        {
                            CountryID = 160,
                            Name = "Romania"
                        },
                        new
                        {
                            CountryID = 161,
                            Name = "Russia"
                        },
                        new
                        {
                            CountryID = 162,
                            Name = "Rwanda"
                        },
                        new
                        {
                            CountryID = 163,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryID = 164,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            CountryID = 165,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryID = 166,
                            Name = "Samoa"
                        },
                        new
                        {
                            CountryID = 167,
                            Name = "San Marino"
                        },
                        new
                        {
                            CountryID = 168,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryID = 169,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            CountryID = 170,
                            Name = "Senegal"
                        },
                        new
                        {
                            CountryID = 171,
                            Name = "Seychelles"
                        },
                        new
                        {
                            CountryID = 172,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            CountryID = 173,
                            Name = "Singapore"
                        },
                        new
                        {
                            CountryID = 174,
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryID = 175,
                            Name = "Slovenia"
                        },
                        new
                        {
                            CountryID = 176,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            CountryID = 177,
                            Name = "Somalia"
                        },
                        new
                        {
                            CountryID = 178,
                            Name = "Somaliland"
                        },
                        new
                        {
                            CountryID = 179,
                            Name = "South Africa"
                        },
                        new
                        {
                            CountryID = 180,
                            Name = "South Korea"
                        },
                        new
                        {
                            CountryID = 181,
                            Name = "South Sudan"
                        },
                        new
                        {
                            CountryID = 182,
                            Name = "Spain"
                        },
                        new
                        {
                            CountryID = 183,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            CountryID = 184,
                            Name = "Sudan"
                        },
                        new
                        {
                            CountryID = 185,
                            Name = "Suriname"
                        },
                        new
                        {
                            CountryID = 186,
                            Name = "Swaziland"
                        },
                        new
                        {
                            CountryID = 187,
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryID = 188,
                            Name = "Switzerland"
                        },
                        new
                        {
                            CountryID = 189,
                            Name = "Syria"
                        },
                        new
                        {
                            CountryID = 190,
                            Name = "Taiwan"
                        },
                        new
                        {
                            CountryID = 191,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            CountryID = 192,
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryID = 193,
                            Name = "Togo"
                        },
                        new
                        {
                            CountryID = 194,
                            Name = "Tonga"
                        },
                        new
                        {
                            CountryID = 195,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryID = 196,
                            Name = "Tunisia"
                        },
                        new
                        {
                            CountryID = 197,
                            Name = "Turkey"
                        },
                        new
                        {
                            CountryID = 198,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            CountryID = 199,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            CountryID = 200,
                            Name = "Uganda"
                        },
                        new
                        {
                            CountryID = 201,
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryID = 202,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            CountryID = 203,
                            Name = "Anguilla"
                        },
                        new
                        {
                            CountryID = 204,
                            Name = "Bermuda"
                        },
                        new
                        {
                            CountryID = 205,
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryID = 206,
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            CountryID = 207,
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            CountryID = 208,
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            CountryID = 209,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            CountryID = 210,
                            Name = "Guernsey"
                        },
                        new
                        {
                            CountryID = 211,
                            Name = "Isle of Man"
                        },
                        new
                        {
                            CountryID = 212,
                            Name = "Jersey"
                        },
                        new
                        {
                            CountryID = 213,
                            Name = "Montserrat"
                        },
                        new
                        {
                            CountryID = 214,
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            CountryID = 215,
                            Name = "Saint Helena"
                        },
                        new
                        {
                            CountryID = 216,
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryID = 217,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryID = 218,
                            Name = "United Republic of Tanzania"
                        },
                        new
                        {
                            CountryID = 219,
                            Name = "American Samoa"
                        },
                        new
                        {
                            CountryID = 220,
                            Name = "Guam"
                        },
                        new
                        {
                            CountryID = 221,
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryID = 222,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            CountryID = 223,
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            CountryID = 224,
                            Name = "United States of America"
                        },
                        new
                        {
                            CountryID = 225,
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryID = 226,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            CountryID = 227,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            CountryID = 228,
                            Name = "Vatican"
                        },
                        new
                        {
                            CountryID = 229,
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryID = 230,
                            Name = "Vietnam"
                        },
                        new
                        {
                            CountryID = 231,
                            Name = "Western Sahara"
                        },
                        new
                        {
                            CountryID = 232,
                            Name = "Yemen"
                        },
                        new
                        {
                            CountryID = 233,
                            Name = "Zambia"
                        },
                        new
                        {
                            CountryID = 234,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("DestinationID");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.HasKey("GenderID");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Guide", b =>
                {
                    b.Property<int>("GuideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuideID"), 1L, 1);

                    b.Property<int>("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.HasKey("GuideID");

                    b.HasIndex("GenderID");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.GuideLanguage", b =>
                {
                    b.Property<int>("GuideID")
                        .HasColumnType("int");

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.HasKey("GuideID", "LanguageID");

                    b.HasIndex("LanguageID");

                    b.ToTable("GuideLanguages");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("varchar(28)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = 1,
                            Name = "Afrikaans"
                        },
                        new
                        {
                            LanguageID = 2,
                            Name = "Albanian"
                        },
                        new
                        {
                            LanguageID = 3,
                            Name = "Amharic"
                        },
                        new
                        {
                            LanguageID = 4,
                            Name = "Arabic"
                        },
                        new
                        {
                            LanguageID = 5,
                            Name = "Armenian"
                        },
                        new
                        {
                            LanguageID = 6,
                            Name = "Aymara"
                        },
                        new
                        {
                            LanguageID = 7,
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            LanguageID = 8,
                            Name = "Bahasa Indonesia"
                        },
                        new
                        {
                            LanguageID = 9,
                            Name = "Bahasa Malaysia"
                        },
                        new
                        {
                            LanguageID = 10,
                            Name = "Belarusian"
                        },
                        new
                        {
                            LanguageID = 11,
                            Name = "Bengali"
                        },
                        new
                        {
                            LanguageID = 12,
                            Name = "Bosnian"
                        },
                        new
                        {
                            LanguageID = 13,
                            Name = "Bulgarian"
                        },
                        new
                        {
                            LanguageID = 14,
                            Name = "Burmanese"
                        },
                        new
                        {
                            LanguageID = 15,
                            Name = "Cantonese"
                        },
                        new
                        {
                            LanguageID = 16,
                            Name = "Catalan"
                        },
                        new
                        {
                            LanguageID = 17,
                            Name = "Chamorro"
                        },
                        new
                        {
                            LanguageID = 18,
                            Name = "Cook Island Maori"
                        },
                        new
                        {
                            LanguageID = 19,
                            Name = "Creole"
                        },
                        new
                        {
                            LanguageID = 20,
                            Name = "Croatian"
                        },
                        new
                        {
                            LanguageID = 21,
                            Name = "Czech"
                        },
                        new
                        {
                            LanguageID = 22,
                            Name = "Danish"
                        },
                        new
                        {
                            LanguageID = 23,
                            Name = "Dari"
                        },
                        new
                        {
                            LanguageID = 24,
                            Name = "Dhivehi"
                        },
                        new
                        {
                            LanguageID = 25,
                            Name = "Dutch"
                        },
                        new
                        {
                            LanguageID = 26,
                            Name = "Dzongkha"
                        },
                        new
                        {
                            LanguageID = 27,
                            Name = "English"
                        },
                        new
                        {
                            LanguageID = 28,
                            Name = "Estonian"
                        },
                        new
                        {
                            LanguageID = 29,
                            Name = "Faroese"
                        },
                        new
                        {
                            LanguageID = 30,
                            Name = "Fijian"
                        },
                        new
                        {
                            LanguageID = 31,
                            Name = "Filipino"
                        },
                        new
                        {
                            LanguageID = 32,
                            Name = "Finnish"
                        },
                        new
                        {
                            LanguageID = 33,
                            Name = "French"
                        },
                        new
                        {
                            LanguageID = 34,
                            Name = "Georgian"
                        },
                        new
                        {
                            LanguageID = 35,
                            Name = "German"
                        },
                        new
                        {
                            LanguageID = 36,
                            Name = "Greek"
                        },
                        new
                        {
                            LanguageID = 37,
                            Name = "Greenlandic"
                        },
                        new
                        {
                            LanguageID = 38,
                            Name = "Guarani"
                        },
                        new
                        {
                            LanguageID = 39,
                            Name = "Hebrew"
                        },
                        new
                        {
                            LanguageID = 40,
                            Name = "Hindi"
                        },
                        new
                        {
                            LanguageID = 41,
                            Name = "Hiri Motu"
                        },
                        new
                        {
                            LanguageID = 42,
                            Name = "Hungarian"
                        },
                        new
                        {
                            LanguageID = 43,
                            Name = "Icelandic"
                        },
                        new
                        {
                            LanguageID = 44,
                            Name = "Indigenous"
                        },
                        new
                        {
                            LanguageID = 45,
                            Name = "Irish"
                        },
                        new
                        {
                            LanguageID = 46,
                            Name = "Italian"
                        },
                        new
                        {
                            LanguageID = 47,
                            Name = "Japanese"
                        },
                        new
                        {
                            LanguageID = 48,
                            Name = "Karakalpakstani"
                        },
                        new
                        {
                            LanguageID = 49,
                            Name = "Kazakh"
                        },
                        new
                        {
                            LanguageID = 50,
                            Name = "Khalkha Mongol"
                        },
                        new
                        {
                            LanguageID = 51,
                            Name = "Khmer"
                        },
                        new
                        {
                            LanguageID = 52,
                            Name = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageID = 53,
                            Name = "Kirundi"
                        },
                        new
                        {
                            LanguageID = 54,
                            Name = "Kiswahili"
                        },
                        new
                        {
                            LanguageID = 55,
                            Name = "Korean"
                        },
                        new
                        {
                            LanguageID = 56,
                            Name = "Kurdish"
                        },
                        new
                        {
                            LanguageID = 57,
                            Name = "Kyrgyz"
                        },
                        new
                        {
                            LanguageID = 58,
                            Name = "Lao"
                        },
                        new
                        {
                            LanguageID = 59,
                            Name = "Latin"
                        },
                        new
                        {
                            LanguageID = 60,
                            Name = "Latvian"
                        },
                        new
                        {
                            LanguageID = 61,
                            Name = "Lingala"
                        },
                        new
                        {
                            LanguageID = 62,
                            Name = "Lithuanian"
                        },
                        new
                        {
                            LanguageID = 63,
                            Name = "Luxembourgish"
                        },
                        new
                        {
                            LanguageID = 64,
                            Name = "Macedonian"
                        },
                        new
                        {
                            LanguageID = 65,
                            Name = "Malagasy"
                        },
                        new
                        {
                            LanguageID = 66,
                            Name = "Malay"
                        },
                        new
                        {
                            LanguageID = 67,
                            Name = "Maltese"
                        },
                        new
                        {
                            LanguageID = 68,
                            Name = "Maori"
                        },
                        new
                        {
                            LanguageID = 69,
                            Name = "Marshallese"
                        },
                        new
                        {
                            LanguageID = 70,
                            Name = "Melanesian pidgin"
                        },
                        new
                        {
                            LanguageID = 71,
                            Name = "Mirandese"
                        },
                        new
                        {
                            LanguageID = 72,
                            Name = "Moldovan"
                        },
                        new
                        {
                            LanguageID = 73,
                            Name = "Montenegrin"
                        },
                        new
                        {
                            LanguageID = 74,
                            Name = "Nauruan"
                        },
                        new
                        {
                            LanguageID = 75,
                            Name = "Ndebele"
                        },
                        new
                        {
                            LanguageID = 76,
                            Name = "Nepali"
                        },
                        new
                        {
                            LanguageID = 77,
                            Name = "Niuean"
                        },
                        new
                        {
                            LanguageID = 78,
                            Name = "Norwegian"
                        },
                        new
                        {
                            LanguageID = 79,
                            Name = "Palauan"
                        },
                        new
                        {
                            LanguageID = 80,
                            Name = "Pashto"
                        },
                        new
                        {
                            LanguageID = 81,
                            Name = "Persian"
                        },
                        new
                        {
                            LanguageID = 82,
                            Name = "Polish"
                        },
                        new
                        {
                            LanguageID = 83,
                            Name = "Polynesian"
                        },
                        new
                        {
                            LanguageID = 84,
                            Name = "Portuguese"
                        },
                        new
                        {
                            LanguageID = 85,
                            Name = "Quechua"
                        },
                        new
                        {
                            LanguageID = 86,
                            Name = "Regional Chinese"
                        },
                        new
                        {
                            LanguageID = 87,
                            Name = "Romanian"
                        },
                        new
                        {
                            LanguageID = 88,
                            Name = "Russian"
                        },
                        new
                        {
                            LanguageID = 89,
                            Name = "Samoan"
                        },
                        new
                        {
                            LanguageID = 90,
                            Name = "Sangho"
                        },
                        new
                        {
                            LanguageID = 91,
                            Name = "Sara"
                        },
                        new
                        {
                            LanguageID = 92,
                            Name = "Serbian"
                        },
                        new
                        {
                            LanguageID = 93,
                            Name = "Shona"
                        },
                        new
                        {
                            LanguageID = 94,
                            Name = "Sinhala"
                        },
                        new
                        {
                            LanguageID = 95,
                            Name = "Slovak"
                        },
                        new
                        {
                            LanguageID = 96,
                            Name = "Slovenian"
                        },
                        new
                        {
                            LanguageID = 97,
                            Name = "Somali"
                        },
                        new
                        {
                            LanguageID = 98,
                            Name = "Sotho"
                        },
                        new
                        {
                            LanguageID = 99,
                            Name = "Spanish"
                        },
                        new
                        {
                            LanguageID = 100,
                            Name = "Standard Chinese or Mandarin"
                        },
                        new
                        {
                            LanguageID = 101,
                            Name = "Swahili"
                        },
                        new
                        {
                            LanguageID = 102,
                            Name = "Swedish"
                        },
                        new
                        {
                            LanguageID = 103,
                            Name = "Tajik"
                        },
                        new
                        {
                            LanguageID = 104,
                            Name = "Tetum"
                        },
                        new
                        {
                            LanguageID = 105,
                            Name = "Thai"
                        },
                        new
                        {
                            LanguageID = 106,
                            Name = "Tigrinya"
                        },
                        new
                        {
                            LanguageID = 107,
                            Name = "Tok Pisin"
                        },
                        new
                        {
                            LanguageID = 108,
                            Name = "Tongan"
                        },
                        new
                        {
                            LanguageID = 109,
                            Name = "Turkish"
                        },
                        new
                        {
                            LanguageID = 110,
                            Name = "Turkmen"
                        },
                        new
                        {
                            LanguageID = 111,
                            Name = "Tuvaluan"
                        },
                        new
                        {
                            LanguageID = 112,
                            Name = "Ukrainian"
                        },
                        new
                        {
                            LanguageID = 113,
                            Name = "Urdu"
                        },
                        new
                        {
                            LanguageID = 114,
                            Name = "Uzbek"
                        },
                        new
                        {
                            LanguageID = 115,
                            Name = "Vietnamese"
                        },
                        new
                        {
                            LanguageID = 116,
                            Name = "siSwati"
                        });
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Nationality", b =>
                {
                    b.Property<int>("NationalityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalityID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.HasKey("NationalityID");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityID = 1,
                            Name = "Afghan"
                        },
                        new
                        {
                            NationalityID = 2,
                            Name = "Albanian"
                        },
                        new
                        {
                            NationalityID = 3,
                            Name = "Andorran"
                        },
                        new
                        {
                            NationalityID = 4,
                            Name = "Angolan"
                        },
                        new
                        {
                            NationalityID = 5,
                            Name = "Argentine"
                        },
                        new
                        {
                            NationalityID = 6,
                            Name = "Armenian"
                        },
                        new
                        {
                            NationalityID = 7,
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            NationalityID = 8,
                            Name = "Bahamian"
                        },
                        new
                        {
                            NationalityID = 9,
                            Name = "Bahraini"
                        },
                        new
                        {
                            NationalityID = 10,
                            Name = "Belarusian"
                        },
                        new
                        {
                            NationalityID = 11,
                            Name = "Belgian"
                        },
                        new
                        {
                            NationalityID = 12,
                            Name = "Bermudian"
                        },
                        new
                        {
                            NationalityID = 13,
                            Name = "Bhutanese"
                        },
                        new
                        {
                            NationalityID = 14,
                            Name = "Botswanan"
                        },
                        new
                        {
                            NationalityID = 15,
                            Name = "Brazilian"
                        },
                        new
                        {
                            NationalityID = 16,
                            Name = "Bruneian"
                        },
                        new
                        {
                            NationalityID = 17,
                            Name = "Bulgarian"
                        },
                        new
                        {
                            NationalityID = 18,
                            Name = "Burundian"
                        },
                        new
                        {
                            NationalityID = 19,
                            Name = "Cambodian"
                        },
                        new
                        {
                            NationalityID = 20,
                            Name = "Cameroonian"
                        },
                        new
                        {
                            NationalityID = 21,
                            Name = "Cayman Islander"
                        },
                        new
                        {
                            NationalityID = 22,
                            Name = "Central African"
                        },
                        new
                        {
                            NationalityID = 23,
                            Name = "Chinese"
                        },
                        new
                        {
                            NationalityID = 24,
                            Name = "Citizen of Seychelles"
                        },
                        new
                        {
                            NationalityID = 25,
                            Name = "Citizen of Vanuatu"
                        },
                        new
                        {
                            NationalityID = 26,
                            Name = "Colombian"
                        },
                        new
                        {
                            NationalityID = 27,
                            Name = "Congolese (DRC)"
                        },
                        new
                        {
                            NationalityID = 28,
                            Name = "Cook Islander"
                        },
                        new
                        {
                            NationalityID = 29,
                            Name = "Cuban"
                        },
                        new
                        {
                            NationalityID = 30,
                            Name = "Cymraes"
                        },
                        new
                        {
                            NationalityID = 31,
                            Name = "Czech"
                        },
                        new
                        {
                            NationalityID = 32,
                            Name = "Danish"
                        },
                        new
                        {
                            NationalityID = 33,
                            Name = "Djiboutian"
                        },
                        new
                        {
                            NationalityID = 34,
                            Name = "Dutch"
                        },
                        new
                        {
                            NationalityID = 35,
                            Name = "East Timorese"
                        },
                        new
                        {
                            NationalityID = 36,
                            Name = "Ecuadorean"
                        },
                        new
                        {
                            NationalityID = 37,
                            Name = "English"
                        },
                        new
                        {
                            NationalityID = 38,
                            Name = "Equatorial Guinean"
                        },
                        new
                        {
                            NationalityID = 39,
                            Name = "Ethiopian"
                        },
                        new
                        {
                            NationalityID = 40,
                            Name = "Faroese"
                        },
                        new
                        {
                            NationalityID = 41,
                            Name = "Fijian"
                        },
                        new
                        {
                            NationalityID = 42,
                            Name = "Finnish"
                        },
                        new
                        {
                            NationalityID = 43,
                            Name = "French"
                        },
                        new
                        {
                            NationalityID = 44,
                            Name = "Gabonese"
                        },
                        new
                        {
                            NationalityID = 45,
                            Name = "Gambian"
                        },
                        new
                        {
                            NationalityID = 46,
                            Name = "Ghanaian"
                        },
                        new
                        {
                            NationalityID = 47,
                            Name = "Gibraltarian"
                        },
                        new
                        {
                            NationalityID = 48,
                            Name = "Greek"
                        },
                        new
                        {
                            NationalityID = 49,
                            Name = "Grenadian"
                        },
                        new
                        {
                            NationalityID = 50,
                            Name = "Guamanian"
                        },
                        new
                        {
                            NationalityID = 51,
                            Name = "Guinean"
                        },
                        new
                        {
                            NationalityID = 52,
                            Name = "Guyanese"
                        },
                        new
                        {
                            NationalityID = 53,
                            Name = "Haitian"
                        },
                        new
                        {
                            NationalityID = 54,
                            Name = "Honduran"
                        },
                        new
                        {
                            NationalityID = 55,
                            Name = "Icelandic"
                        },
                        new
                        {
                            NationalityID = 56,
                            Name = "Indian"
                        },
                        new
                        {
                            NationalityID = 57,
                            Name = "Iraqi"
                        },
                        new
                        {
                            NationalityID = 58,
                            Name = "Italian"
                        },
                        new
                        {
                            NationalityID = 59,
                            Name = "Irish"
                        },
                        new
                        {
                            NationalityID = 60,
                            Name = "Ivorian"
                        },
                        new
                        {
                            NationalityID = 61,
                            Name = "Jamaican"
                        },
                        new
                        {
                            NationalityID = 62,
                            Name = "Japanese"
                        },
                        new
                        {
                            NationalityID = 63,
                            Name = "Kazakh"
                        },
                        new
                        {
                            NationalityID = 64,
                            Name = "Kenyan"
                        },
                        new
                        {
                            NationalityID = 65,
                            Name = "Kosovan"
                        },
                        new
                        {
                            NationalityID = 66,
                            Name = "Kuwaiti"
                        },
                        new
                        {
                            NationalityID = 67,
                            Name = "Lao"
                        },
                        new
                        {
                            NationalityID = 68,
                            Name = "Latvian"
                        },
                        new
                        {
                            NationalityID = 69,
                            Name = "Libyan"
                        },
                        new
                        {
                            NationalityID = 70,
                            Name = "Liechtenstein citizen"
                        },
                        new
                        {
                            NationalityID = 71,
                            Name = "Macanese"
                        },
                        new
                        {
                            NationalityID = 72,
                            Name = "Macedonian"
                        },
                        new
                        {
                            NationalityID = 73,
                            Name = "Malaysian"
                        },
                        new
                        {
                            NationalityID = 74,
                            Name = "Maldivian"
                        },
                        new
                        {
                            NationalityID = 75,
                            Name = "Marshallese"
                        },
                        new
                        {
                            NationalityID = 76,
                            Name = "Martiniquais"
                        },
                        new
                        {
                            NationalityID = 77,
                            Name = "Mexican"
                        },
                        new
                        {
                            NationalityID = 78,
                            Name = "Micronesian"
                        },
                        new
                        {
                            NationalityID = 79,
                            Name = "Mongolian"
                        },
                        new
                        {
                            NationalityID = 80,
                            Name = "Montenegrin"
                        },
                        new
                        {
                            NationalityID = 81,
                            Name = "Mosotho"
                        },
                        new
                        {
                            NationalityID = 82,
                            Name = "Mozambican"
                        },
                        new
                        {
                            NationalityID = 83,
                            Name = "Namibian"
                        },
                        new
                        {
                            NationalityID = 84,
                            Name = "Nauruan"
                        },
                        new
                        {
                            NationalityID = 85,
                            Name = "Nicaraguan"
                        },
                        new
                        {
                            NationalityID = 86,
                            Name = "Nigerian"
                        },
                        new
                        {
                            NationalityID = 87,
                            Name = "North Korean"
                        },
                        new
                        {
                            NationalityID = 88,
                            Name = "Northern Irish"
                        },
                        new
                        {
                            NationalityID = 89,
                            Name = "Omani"
                        },
                        new
                        {
                            NationalityID = 90,
                            Name = "Pakistani"
                        },
                        new
                        {
                            NationalityID = 91,
                            Name = "Palauan"
                        },
                        new
                        {
                            NationalityID = 92,
                            Name = "Papua New Guinean"
                        },
                        new
                        {
                            NationalityID = 93,
                            Name = "Paraguayan"
                        },
                        new
                        {
                            NationalityID = 94,
                            Name = "Polish"
                        },
                        new
                        {
                            NationalityID = 95,
                            Name = "Portuguese"
                        },
                        new
                        {
                            NationalityID = 96,
                            Name = "Qatari"
                        },
                        new
                        {
                            NationalityID = 97,
                            Name = "Romanian"
                        },
                        new
                        {
                            NationalityID = 98,
                            Name = "Russian"
                        },
                        new
                        {
                            NationalityID = 99,
                            Name = "Salvadorean"
                        },
                        new
                        {
                            NationalityID = 100,
                            Name = "Sammarinese"
                        },
                        new
                        {
                            NationalityID = 101,
                            Name = "Saudi Arabian"
                        },
                        new
                        {
                            NationalityID = 102,
                            Name = "Scottish"
                        },
                        new
                        {
                            NationalityID = 103,
                            Name = "Sierra Leonean"
                        },
                        new
                        {
                            NationalityID = 104,
                            Name = "Slovenian"
                        },
                        new
                        {
                            NationalityID = 105,
                            Name = "Solomon Islander"
                        },
                        new
                        {
                            NationalityID = 106,
                            Name = "South Korean"
                        },
                        new
                        {
                            NationalityID = 107,
                            Name = "South Sudanese"
                        },
                        new
                        {
                            NationalityID = 108,
                            Name = "St Helenian"
                        },
                        new
                        {
                            NationalityID = 109,
                            Name = "St Lucian"
                        },
                        new
                        {
                            NationalityID = 110,
                            Name = "Surinamese"
                        },
                        new
                        {
                            NationalityID = 111,
                            Name = "Swazi"
                        },
                        new
                        {
                            NationalityID = 112,
                            Name = "Syrian"
                        },
                        new
                        {
                            NationalityID = 113,
                            Name = "Taiwanese"
                        },
                        new
                        {
                            NationalityID = 114,
                            Name = "Tajik"
                        },
                        new
                        {
                            NationalityID = 115,
                            Name = "Togolese"
                        },
                        new
                        {
                            NationalityID = 116,
                            Name = "Tongan"
                        },
                        new
                        {
                            NationalityID = 117,
                            Name = "Tunisian"
                        },
                        new
                        {
                            NationalityID = 118,
                            Name = "Turkish"
                        },
                        new
                        {
                            NationalityID = 119,
                            Name = "Tuvaluan"
                        },
                        new
                        {
                            NationalityID = 120,
                            Name = "Ugandan"
                        },
                        new
                        {
                            NationalityID = 121,
                            Name = "Ukrainian"
                        },
                        new
                        {
                            NationalityID = 122,
                            Name = "Vatican citizen"
                        },
                        new
                        {
                            NationalityID = 123,
                            Name = "Vincentian"
                        },
                        new
                        {
                            NationalityID = 124,
                            Name = "Wallisian"
                        },
                        new
                        {
                            NationalityID = 125,
                            Name = "Welsh"
                        },
                        new
                        {
                            NationalityID = 126,
                            Name = "Yemeni"
                        },
                        new
                        {
                            NationalityID = 127,
                            Name = "Zambian"
                        },
                        new
                        {
                            NationalityID = 128,
                            Name = "Zimbabwean"
                        });
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Tour", b =>
                {
                    b.Property<int>("TourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TourID");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.TourDestination", b =>
                {
                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.HasKey("TourID", "DestinationID");

                    b.HasIndex("DestinationID");

                    b.ToTable("TourDestinations");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Tourist", b =>
                {
                    b.Property<int>("TouristID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TouristID"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<int>("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NationalityID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("TouristID");

                    b.HasIndex("CountryID");

                    b.HasIndex("GenderID");

                    b.HasIndex("NationalityID");

                    b.ToTable("Tourists");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.TourParticipant", b =>
                {
                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("TouristID")
                        .HasColumnType("int");

                    b.HasKey("BookingID", "TouristID");

                    b.HasIndex("TouristID");

                    b.ToTable("TourParticipants");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TourCompany.Domain.Entities.Guide", "Guide")
                        .WithMany("Tours")
                        .HasForeignKey("GuideID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourCompany.Domain.Entities.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Guide", b =>
                {
                    b.HasOne("TourCompany.Domain.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.GuideLanguage", b =>
                {
                    b.HasOne("TourCompany.Domain.Entities.Guide", "Guide")
                        .WithMany("Languages")
                        .HasForeignKey("GuideID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourCompany.Domain.Entities.Language", "Language")
                        .WithMany("Guides")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.TourDestination", b =>
                {
                    b.HasOne("TourCompany.Domain.Entities.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourCompany.Domain.Entities.Tour", "Tour")
                        .WithMany("Destinations")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Tourist", b =>
                {
                    b.HasOne("TourCompany.Domain.Entities.Country", "Country")
                        .WithMany("Tourists")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourCompany.Domain.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourCompany.Domain.Entities.Nationality", "Nationality")
                        .WithMany("Tourists")
                        .HasForeignKey("NationalityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Gender");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.TourParticipant", b =>
                {
                    b.HasOne("TourCompany.Domain.Entities.Booking", "Booking")
                        .WithMany("Tourists")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TourCompany.Domain.Entities.Tourist", "Tourist")
                        .WithMany("Tours")
                        .HasForeignKey("TouristID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Tourists");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Country", b =>
                {
                    b.Navigation("Tourists");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Guide", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Language", b =>
                {
                    b.Navigation("Guides");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Nationality", b =>
                {
                    b.Navigation("Tourists");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TourCompany.Domain.Entities.Tourist", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
