using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TourCompany.Domain.Entities;

namespace TourCompany.Infrastructure.Persistence.Configurations
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.Property(c => c.Name)
                .HasColumnType("varchar")
                .HasMaxLength(36);

            int countryID = 1;
            var countries = new Country[]
            {
                new Country(countryID++, "Afghanistan"),
                new Country(countryID++, "Albania"),
                new Country(countryID++, "Algeria"),
                new Country(countryID++, "Andorra"),
                new Country(countryID++, "Angola"),
                new Country(countryID++, "Antigua and Barbuda"),
                new Country(countryID++, "Argentina"),
                new Country(countryID++, "Armenia"),
                new Country(countryID++, "Australia"),
                new Country(countryID++, "Norfolk Island"),
                new Country(countryID++, "Austria"),
                new Country(countryID++, "Azerbaijan"),
                new Country(countryID++, "Bahrain"),
                new Country(countryID++, "Bangladesh"),
                new Country(countryID++, "Barbados"),
                new Country(countryID++, "Belarus"),
                new Country(countryID++, "Belgium"),
                new Country(countryID++, "Belize"),
                new Country(countryID++, "Benin"),
                new Country(countryID++, "Bhutan"),
                new Country(countryID++, "Bolivia"),
                new Country(countryID++, "Bosnia and Herzegovina"),
                new Country(countryID++, "Botswana"),
                new Country(countryID++, "Brazil"),
                new Country(countryID++, "Brunei"),
                new Country(countryID++, "Bulgaria"),
                new Country(countryID++, "Burkina Faso"),
                new Country(countryID++, "Burundi"),
                new Country(countryID++, "Cambodia"),
                new Country(countryID++, "Cameroon"),
                new Country(countryID++, "Canada"),
                new Country(countryID++, "Cape Verde"),
                new Country(countryID++, "Central African Republic"),
                new Country(countryID++, "Chad"),
                new Country(countryID++, "Chile"),
                new Country(countryID++, "China"),
                new Country(countryID++, "Hong Kong S.A.R."),
                new Country(countryID++, "Colombia"),
                new Country(countryID++, "Comoros"),
                new Country(countryID++, "Costa Rica"),
                new Country(countryID++, "Croatia"),
                new Country(countryID++, "Cuba"),
                new Country(countryID++, "Cyprus"),
                new Country(countryID++, "Czech Republic"),
                new Country(countryID++, "Democratic Republic of the Congo"),
                new Country(countryID++, "Denmark"),
                new Country(countryID++, "Faroe Islands"),
                new Country(countryID++, "Greenland"),
                new Country(countryID++, "Djibouti"),
                new Country(countryID++, "Dominica"),
                new Country(countryID++, "Dominican Republic"),
                new Country(countryID++, "East Timor"),
                new Country(countryID++, "Ecuador"),
                new Country(countryID++, "Egypt"),
                new Country(countryID++, "El Salvador"),
                new Country(countryID++, "Equatorial Guinea"),
                new Country(countryID++, "Eritrea"),
                new Country(countryID++, "Estonia"),
                new Country(countryID++, "Ethiopia"),
                new Country(countryID++, "Federated States of Micronesia"),
                new Country(countryID++, "Fiji"),
                new Country(countryID++, "Aland"),
                new Country(countryID++, "Finland"),
                new Country(countryID++, "Clipperton Island"),
                new Country(countryID++, "France"),
                new Country(countryID++, "French Polynesia"),
                new Country(countryID++, "New Caledonia"),
                new Country(countryID++, "Saint Barthelemy"),
                new Country(countryID++, "Saint Martin"),
                new Country(countryID++, "Saint Pierre and Miquelon"),
                new Country(countryID++, "Wallis and Futuna"),
                new Country(countryID++, "Gabon"),
                new Country(countryID++, "Gambia"),
                new Country(countryID++, "Georgia"),
                new Country(countryID++, "Germany"),
                new Country(countryID++, "Ghana"),
                new Country(countryID++, "Greece"),
                new Country(countryID++, "Grenada"),
                new Country(countryID++, "Guatemala"),
                new Country(countryID++, "Guinea"),
                new Country(countryID++, "Guinea Bissau"),
                new Country(countryID++, "Guyana"),
                new Country(countryID++, "Haiti"),
                new Country(countryID++, "Honduras"),
                new Country(countryID++, "Hungary"),
                new Country(countryID++, "Iceland"),
                new Country(countryID++, "India"),
                new Country(countryID++, "Indonesia"),
                new Country(countryID++, "Iran"),
                new Country(countryID++, "Iraq"),
                new Country(countryID++, "Ireland"),
                new Country(countryID++, "Israel"),
                new Country(countryID++, "Palestine"),
                new Country(countryID++, "Italy"),
                new Country(countryID++, "Ivory Coast"),
                new Country(countryID++, "Jamaica"),
                new Country(countryID++, "Japan"),
                new Country(countryID++, "Jordan"),
                new Country(countryID++, "Kazakhstan"),
                new Country(countryID++, "Kenya"),
                new Country(countryID++, "Kiribati"),
                new Country(countryID++, "Kosovo"),
                new Country(countryID++, "Kuwait"),
                new Country(countryID++, "Kyrgyzstan"),
                new Country(countryID++, "Laos"),
                new Country(countryID++, "Latvia"),
                new Country(countryID++, "Lebanon"),
                new Country(countryID++, "Lesotho"),
                new Country(countryID++, "Liberia"),
                new Country(countryID++, "Libya"),
                new Country(countryID++, "Liechtenstein"),
                new Country(countryID++, "Lithuania"),
                new Country(countryID++, "Luxembourg"),
                new Country(countryID++, "Macedonia"),
                new Country(countryID++, "Madagascar"),
                new Country(countryID++, "Malawi"),
                new Country(countryID++, "Malaysia"),
                new Country(countryID++, "Maldives"),
                new Country(countryID++, "Mali"),
                new Country(countryID++, "Malta"),
                new Country(countryID++, "Marshall Islands"),
                new Country(countryID++, "Mauritania"),
                new Country(countryID++, "Mauritius"),
                new Country(countryID++, "Mexico"),
                new Country(countryID++, "Moldova"),
                new Country(countryID++, "Monaco"),
                new Country(countryID++, "Mongolia"),
                new Country(countryID++, "Montenegro"),
                new Country(countryID++, "Morocco"),
                new Country(countryID++, "Mozambique"),
                new Country(countryID++, "Myanmar"),
                new Country(countryID++, "Namibia"),
                new Country(countryID++, "Nauru"),
                new Country(countryID++, "Nepal"),
                new Country(countryID++, "Aruba"),
                new Country(countryID++, "Netherlands"),
                new Country(countryID++, "Sint Maarten"),
                new Country(countryID++, "Cook Islands"),
                new Country(countryID++, "New Zealand"),
                new Country(countryID++, "Niue"),
                new Country(countryID++, "Nicaragua"),
                new Country(countryID++, "Niger"),
                new Country(countryID++, "Nigeria"),
                new Country(countryID++, "North Korea"),
                new Country(countryID++, "Northern Cyprus"),
                new Country(countryID++, "Norway"),
                new Country(countryID++, "Oman"),
                new Country(countryID++, "Pakistan"),
                new Country(countryID++, "Palau"),
                new Country(countryID++, "Panama"),
                new Country(countryID++, "Papua New Guinea"),
                new Country(countryID++, "Paraguay"),
                new Country(countryID++, "Peru"),
                new Country(countryID++, "Philippines"),
                new Country(countryID++, "Poland"),
                new Country(countryID++, "Portugal"),
                new Country(countryID++, "Qatar"),
                new Country(countryID++, "Republic of Congo"),
                new Country(countryID++, "Serbia"),
                new Country(countryID++, "Romania"),
                new Country(countryID++, "Russia"),
                new Country(countryID++, "Rwanda"),
                new Country(countryID++, "Saint Kitts and Nevis"),
                new Country(countryID++, "Saint Lucia"),
                new Country(countryID++, "Saint Vincent and the Grenadines"),
                new Country(countryID++, "Samoa"),
                new Country(countryID++, "San Marino"),
                new Country(countryID++, "Sao Tome and Principe"),
                new Country(countryID++, "Saudi Arabia"),
                new Country(countryID++, "Senegal"),
                new Country(countryID++, "Seychelles"),
                new Country(countryID++, "Sierra Leone"),
                new Country(countryID++, "Singapore"),
                new Country(countryID++, "Slovakia"),
                new Country(countryID++, "Slovenia"),
                new Country(countryID++, "Solomon Islands"),
                new Country(countryID++, "Somalia"),
                new Country(countryID++, "Somaliland"),
                new Country(countryID++, "South Africa"),
                new Country(countryID++, "South Korea"),
                new Country(countryID++, "South Sudan"),
                new Country(countryID++, "Spain"),
                new Country(countryID++, "Sri Lanka"),
                new Country(countryID++, "Sudan"),
                new Country(countryID++, "Suriname"),
                new Country(countryID++, "Swaziland"),
                new Country(countryID++, "Sweden"),
                new Country(countryID++, "Switzerland"),
                new Country(countryID++, "Syria"),
                new Country(countryID++, "Taiwan"),
                new Country(countryID++, "Tajikistan"),
                new Country(countryID++, "Thailand"),
                new Country(countryID++, "Togo"),
                new Country(countryID++, "Tonga"),
                new Country(countryID++, "Trinidad and Tobago"),
                new Country(countryID++, "Tunisia"),
                new Country(countryID++, "Turkey"),
                new Country(countryID++, "Turkmenistan"),
                new Country(countryID++, "Tuvalu"),
                new Country(countryID++, "Uganda"),
                new Country(countryID++, "Ukraine"),
                new Country(countryID++, "United Arab Emirates"),
                new Country(countryID++, "Anguilla"),
                new Country(countryID++, "Bermuda"),
                new Country(countryID++, "British Indian Ocean Territory"),
                new Country(countryID++, "British Virgin Islands"),
                new Country(countryID++, "Cayman Islands"),
                new Country(countryID++, "Falkland Islands"),
                new Country(countryID++, "Gibraltar"),
                new Country(countryID++, "Guernsey"),
                new Country(countryID++, "Isle of Man"),
                new Country(countryID++, "Jersey"),
                new Country(countryID++, "Montserrat"),
                new Country(countryID++, "Pitcairn Islands"),
                new Country(countryID++, "Saint Helena"),
                new Country(countryID++, "Turks and Caicos Islands"),
                new Country(countryID++, "United Kingdom"),
                new Country(countryID++, "United Republic of Tanzania"),
                new Country(countryID++, "American Samoa"),
                new Country(countryID++, "Guam"),
                new Country(countryID++, "Northern Mariana Islands"),
                new Country(countryID++, "Puerto Rico"),
                new Country(countryID++, "United States Minor Outlying Islands"),
                new Country(countryID++, "United States of America"),
                new Country(countryID++, "Uruguay"),
                new Country(countryID++, "Uzbekistan"),
                new Country(countryID++, "Vanuatu"),
                new Country(countryID++, "Vatican"),
                new Country(countryID++, "Venezuela"),
                new Country(countryID++, "Vietnam"),
                new Country(countryID++, "Western Sahara"),
                new Country(countryID++, "Yemen"),
                new Country(countryID++, "Zambia"),
                new Country(countryID++, "Zimbabwe"),
            };
            builder.HasData(countries);
        }
    }
}
