using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TourCompany.Domain.Entities;

namespace TourCompany.Infrastructure.Persistence.Configurations
{
    public class LanguageConfiguration : IEntityTypeConfiguration<Language>
    {
        public void Configure(EntityTypeBuilder<Language> builder)
        {
            builder.Property(l => l.Name)
                .HasColumnType("varchar")
                .HasMaxLength(28);

            int languageID = 1;
            var languages = new Language[]
            {
                new Language(languageID++, "Afrikaans"),
                new Language(languageID++, "Albanian"),
                new Language(languageID++, "Amharic"),
                new Language(languageID++, "Arabic"),
                new Language(languageID++, "Armenian"),
                new Language(languageID++, "Aymara"),
                new Language(languageID++, "Azerbaijani"),
                new Language(languageID++, "Bahasa Indonesia"),
                new Language(languageID++, "Bahasa Malaysia"),
                new Language(languageID++, "Belarusian"),
                new Language(languageID++, "Bengali"),
                new Language(languageID++, "Bosnian"),
                new Language(languageID++, "Bulgarian"),
                new Language(languageID++, "Burmanese"),
                new Language(languageID++, "Cantonese"),
                new Language(languageID++, "Catalan"),
                new Language(languageID++, "Chamorro"),
                new Language(languageID++, "Cook Island Maori"),
                new Language(languageID++, "Creole"),
                new Language(languageID++, "Croatian"),
                new Language(languageID++, "Czech"),
                new Language(languageID++, "Danish"),
                new Language(languageID++, "Dari"),
                new Language(languageID++, "Dhivehi"),
                new Language(languageID++, "Dutch"),
                new Language(languageID++, "Dzongkha"),
                new Language(languageID++, "English"),
                new Language(languageID++, "Estonian"),
                new Language(languageID++, "Faroese"),
                new Language(languageID++, "Fijian"),
                new Language(languageID++, "Filipino"),
                new Language(languageID++, "Finnish"),
                new Language(languageID++, "French"),
                new Language(languageID++, "Georgian"),
                new Language(languageID++, "German"),
                new Language(languageID++, "Greek"),
                new Language(languageID++, "Greenlandic"),
                new Language(languageID++, "Guarani"),
                new Language(languageID++, "Hebrew"),
                new Language(languageID++, "Hindi"),
                new Language(languageID++, "Hiri Motu"),
                new Language(languageID++, "Hungarian"),
                new Language(languageID++, "Icelandic"),
                new Language(languageID++, "Indigenous"),
                new Language(languageID++, "Irish"),
                new Language(languageID++, "Italian"),
                new Language(languageID++, "Japanese"),
                new Language(languageID++, "Karakalpakstani"),
                new Language(languageID++, "Kazakh"),
                new Language(languageID++, "Khalkha Mongol"),
                new Language(languageID++, "Khmer"),
                new Language(languageID++, "Kinyarwanda"),
                new Language(languageID++, "Kirundi"),
                new Language(languageID++, "Kiswahili"),
                new Language(languageID++, "Korean"),
                new Language(languageID++, "Kurdish"),
                new Language(languageID++, "Kyrgyz"),
                new Language(languageID++, "Lao"),
                new Language(languageID++, "Latin"),
                new Language(languageID++, "Latvian"),
                new Language(languageID++, "Lingala"),
                new Language(languageID++, "Lithuanian"),
                new Language(languageID++, "Luxembourgish"),
                new Language(languageID++, "Macedonian"),
                new Language(languageID++, "Malagasy"),
                new Language(languageID++, "Malay"),
                new Language(languageID++, "Maltese"),
                new Language(languageID++, "Maori"),
                new Language(languageID++, "Marshallese"),
                new Language(languageID++, "Melanesian pidgin"),
                new Language(languageID++, "Mirandese"),
                new Language(languageID++, "Moldovan"),
                new Language(languageID++, "Montenegrin"),
                new Language(languageID++, "Nauruan"),
                new Language(languageID++, "Ndebele"),
                new Language(languageID++, "Nepali"),
                new Language(languageID++, "Niuean"),
                new Language(languageID++, "Norwegian"),
                new Language(languageID++, "Palauan"),
                new Language(languageID++, "Pashto"),
                new Language(languageID++, "Persian"),
                new Language(languageID++, "Polish"),
                new Language(languageID++, "Polynesian"),
                new Language(languageID++, "Portuguese"),
                new Language(languageID++, "Quechua"),
                new Language(languageID++, "Regional Chinese"),
                new Language(languageID++, "Romanian"),
                new Language(languageID++, "Russian"),
                new Language(languageID++, "Samoan"),
                new Language(languageID++, "Sangho"),
                new Language(languageID++, "Sara"),
                new Language(languageID++, "Serbian"),
                new Language(languageID++, "Shona"),
                new Language(languageID++, "Sinhala"),
                new Language(languageID++, "Slovak"),
                new Language(languageID++, "Slovenian"),
                new Language(languageID++, "Somali"),
                new Language(languageID++, "Sotho"),
                new Language(languageID++, "Spanish"),
                new Language(languageID++, "Standard Chinese or Mandarin"),
                new Language(languageID++, "Swahili"),
                new Language(languageID++, "Swedish"),
                new Language(languageID++, "Tajik"),
                new Language(languageID++, "Tetum"),
                new Language(languageID++, "Thai"),
                new Language(languageID++, "Tigrinya"),
                new Language(languageID++, "Tok Pisin"),
                new Language(languageID++, "Tongan"),
                new Language(languageID++, "Turkish"),
                new Language(languageID++, "Turkmen"),
                new Language(languageID++, "Tuvaluan"),
                new Language(languageID++, "Ukrainian"),
                new Language(languageID++, "Urdu"),
                new Language(languageID++, "Uzbek"),
                new Language(languageID++, "Vietnamese"),
                new Language(languageID++, "siSwati"),
            };
            builder.HasData(languages);
        }
    }
}
